### ISSUE TITLE
TOML not being ignored

### ISSUE THREAD

**Issue by simov** [wooorm/remark-frontmatter#1]
Isn't the TOML front matter supposed to be ignored, just like YAML is being ignored?
![toml](https://user-images.githubusercontent.com/1694112/31369905-4d54c71a-ad90-11e7-8f02-649d1ea03546.png)

```markdown
+++
title = Headline level one
tags = [ "tag1", "tag2", "tag3" ]
description = something
+++

This page contains TOML front matter:


    +++
    title = Headline level one
    tags = [ "tag1", "tag2", "tag3" ]
    description = something
    +++


It should be ignored if you use the `Remark` compiler.
```

And this is my setup:

```js
unified()
      .use(remark.parse, {..})
      .use(remark.stringify)
      .use(remarkSlug)
      .use(remarkFrontmatter, ['yaml', 'toml'])
      .use(remarkHTML, {..})
      .processSync(markdown)
      .contents
```

**Comment by wooorm** [comment]
TOML is supported, that’s why you don’t see pluses showing up, but not ignored when compiling to HTML. Could you create a PR to [add `toml: ignore` in `mdast-util-to-hast`](https://github.com/syntax-tree/mdast-util-to-hast/blob/a8910c9817145a367b1ae7d2c3a8b4b8e40150d2/lib/handlers/index.js#L26)?

Finally: where are `remark.parse` and `remark.stringify` coming from? are they results of loading `remark-parse` and `remark-stringify`, or do they live on `remark`?

**Comment by simov** [comment]
> TOML is supported, that’s why you don’t see pluses showing up, but not ignored when compiling to HTML. Could you create a PR to add toml: ignore in mdast-util-to-hast?

Sure!

> Finally: where are remark.parse and remark.stringify coming from? are they results of loading remark-parse and remark-stringify, or do they live on remark?

That's just the way I [build remark](https://github.com/simov/remark/commit/c997e7342f07af2cae4d43529653a23da9c8c319) because I have to pass options to `parse`. Is there a better way to do it?

**Comment by wooorm** [comment]
> That's just the way I build remark because I have to pass options to parse. Is there a better way to do it?

Yes, just require `unified`, `remark-parse`, and `remark-stringify` (if you need it) on their own! No need to use `remark` if you don’t need `remark-parse` or `remark-stringify`!

So, for example:

```js
var unified = require('unified')
var parse = require('remark-parse')
var slug = require('remark-slug')

unified()
  .use(parse, {..})
  .use(slug)
  // ...
```

Or pass options like so:

```js
var remark = require('remark')
var slug = require('remark-slug')

remark()
  .data('settings', {..})
  .use(slug)
  // ...
